from .taskdetail_get_usecase import TaskDetailGetUseCase
from .taskdetail_getall_usecase import TaskDetailGetAllUseCase
from .taskdetail_post_usecase import TaskDetailPostUseCase
from .taskdetail_remove_usecase import TaskDetailRemoveUseCase
from .taskdetail_update_usecase import TaskDetailUpdateUseCase
