"""delete shift status

Revision ID: d72a30056ffc
Revises: 4e5094076185
Create Date: 2026-01-07 13:22:44.605120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd72a30056ffc'
down_revision: Union[str, Sequence[str], None] = '4e5094076185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift', sa.Column('status', postgresql.ENUM('before_hiring', 'hiring', 'decide_assignees', 'archive', name='shiftstate'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
